import Foundation
import AVFoundation
import CoreGraphics

// Runs Trace's own pipeline over a video file and prints what the app would say
// about it, without a simulator, a gym, or a phone.
//
// Every engine here is the shipped one, compiled from the app's sources. The
// only thing this file does is what `ClimbAnalyzer` does on the device: track,
// measure, find, grade. It exists because until now the analysis had only ever
// met synthetic climbers, and a synthetic climber is generated by the same
// assumptions the analysis is built on, so agreeing with one proves nothing.
//
// Usage: traceanalyze <video> [more videos...]

func line(_ s: String = "") { print(s) }

func pct(_ x: Double) -> String { "\(Int((x * 100).rounded()))%" }

func number(_ x: Double?, _ places: Int = 2) -> String {
    guard let x else { return "—" }
    return String(format: "%.\(places)f", x)
}

func report(_ url: URL) async throws {
    line("── \(url.lastPathComponent)")

    let asset = AVURLAsset(url: url)
    let duration = CMTimeGetSeconds(try await asset.load(.duration))
    if let track = try await asset.loadTracks(withMediaType: .video).first {
        let size = try await track.load(.naturalSize)
        let fps = try await track.load(.nominalFrameRate)
        line("   \(Int(size.width))×\(Int(size.height)) at \(String(format: "%.0f", fps)) fps, \(String(format: "%.1f", duration))s")
    }

    if let camera = try await CameraMotion.read(url: url) {
        line(String(format: "   camera travelled %.2f frame heights (drift %.2f, %.0f%% registered) → %@",
                    camera.travel, camera.drift, camera.confidence * 100,
                    camera.isStatic ? "still" : "MOVING, so nothing below about where the body went is about the body"))
    }

    var lastReported = -1
    let frames = try await PoseTracker.track(url: url) { p in
        let step = Int(p * 10)
        if step > lastReported { lastReported = step; FileHandle.standardError.write("·".data(using: .utf8)!) }
    }
    FileHandle.standardError.write("\n".data(using: .utf8)!)

    let tracked = frames.filter { $0.com != nil }
    line("   tracked \(tracked.count) of \(frames.count) frames (\(pct(Double(tracked.count) / Double(max(frames.count, 1)))))")

    let metrics = MetricsEngine.compute(frames: frames)
    let climbing = MetricsEngine.ascent(frames)
    line("   ascent \(climbing.count) frames")

    guard metrics.isTrustworthy else {
        line("   NOT TRUSTWORTHY: Trace would refuse to grade this clip.")
        line("   tracking confidence \(pct(metrics.trackingConfidence)), needs 55%")
        return
    }

    line()
    line("   Metrics")
    line("     tracking        \(pct(metrics.trackingConfidence))")
    line("     duration        \(number(metrics.duration, 1))s")
    line("     entropy         \(number(metrics.entropy))")
    line("     moving jerk     \(number(metrics.movingJerk))")
    line("     whole-clip jerk \(number(metrics.logJerk))")
    line("     path ratio      \(number(metrics.pathRatio))")
    line("     static elbow    \(number(metrics.staticElbowAngle, 1))°")
    line("     pauses          \(metrics.pauseCount), \(number(metrics.pauseTotal, 1))s total")
    line("     foot shuffles   \(metrics.footAdjustments)")
    line("     COM off feet    \(number(metrics.comOffsetFromFeet)) hip widths (resting only)")
    line("     bracketed       \(pct(metrics.bracketedFraction))")
    line("     move waste      \(metrics.moveWaste.map { pct($0) } ?? "—")")
    line("     dynamic timing  \(metrics.hasDynamicMoves ? number(metrics.meanDeadpointError, 0) + "ms" : "no dynamic moves")")

    if let moves = MoveEngine.read(frames: climbing) {
        line("     moves           \(moves.moves.count), \(pct(moves.waste)) of travel off-line")
    } else {
        line("     moves           none found")
    }

    let climb = Climb(recordedAt: Date(), videoFilename: url.lastPathComponent,
                      label: url.deletingPathExtension().lastPathComponent,
                      metrics: metrics,
                      findings: FindingEngine.findings(from: metrics, frames: climbing,
                                                       priorJerk: []),
                      frames: frames,
                      sent: nil, gymID: nil)

    line()
    if let reading = EfficiencyEngine.read(climb) {
        line("   VERDICT: \(reading.grade.label) — \(pct(reading.cost)) wasted")
        for c in reading.components.sorted(by: { $0.contribution > $1.contribution }) {
            line("     \(c.name): \(c.detail)")
        }
    } else {
        line("   VERDICT: none, the clip could not be graded")
    }

    line()
    line("   Findings")
    if climb.findings.isEmpty {
        line("     none")
    } else {
        for f in climb.findings { line("     • [\(f.timecode)] \(f.kind.title) — \(f.message)") }
    }

    switch OutcomeEngine.outcome(frames: frames) {
    case .topped:  line("   Outcome: topped out")
    case .fell:    line("   Outcome: came off")
    case .unclear: line("   Outcome: unclear, left to the climber")
    }
    line()
}

let paths = Array(CommandLine.arguments.dropFirst())
guard !paths.isEmpty else {
    FileHandle.standardError.write("usage: traceanalyze <video> [...]\n".data(using: .utf8)!)
    exit(2)
}

let done = DispatchSemaphore(value: 0)
Task {
    for path in paths {
        do { try await report(URL(fileURLWithPath: path)) }
        catch { line("   FAILED: \(error)") }
    }
    done.signal()
}
done.wait()
